### ISSUE TITLE
Library use case and intent?

### ISSUE THREAD

**Issue by markerikson** [mike-es6/reslice#1]
Hi.  Ran across this as I was browsing Github for Redux-related projects.  Skimming through the code, it looks like you're doing _something_ interesting, but I can't quite tell what the intended use case is or how you'd use this library.  Could you give some details on what you're doing here?

**Comment by mike-es6** [comment]
Thanks for the interest .... work in progress ATM (and that includes it being my first github repo!). So like the front page says: in progress, come back later!

But since you ask: its a way to put an object-like interface over Redux, so the actions and selectors can be automatically bound to the objects returned by Redux reducer functions. Its being used (a bit experminentally ATM) in a large React application.

More news anon!

**Comment by markerikson** [comment]
Interesting.  Yeah, I'd love to see some examples or code snippets to get a better understanding how it works.

FYI, I'm a Redux maintainer, and I also keep a big list of Redux-related addons at https://github.com/markerikson/redux-ecosystem-links .  If you do get this to a point where you feel it's usable by the public, please submit a PR to add it to my list.

**Comment by mike-es6** [comment]
Thanks. WIll do, working on the redoubtable ToDo application :)

**Comment by mike-es6** [comment]
Hi. Ready to go, which section of your list would you suggest .... entity-collection-management ?

**Comment by markerikson** [comment]
I actually did add it already - it's under the ["Variations"](https://github.com/markerikson/redux-ecosystem-links/blob/master/variations.md) category.

**Comment by mike-es6** [comment]
Col. Thanks! I'll close the issue.
